INPUT_IMAGE = "test-image.jpg"
TILE_FOLDER = "tiles"
IMAGE_EXTENSIONS = (".png", ".jpg", ".jpeg")

TARGET_SIZE = 512

GRID_SIZE = 64
TILE_SIZE = TARGET_SIZE // GRID_SIZE  

K_COLORS = 32
KMEANS_MAX_ITER = 10
KMEANS_EPSILON = 1.0
KMEANS_ATTEMPTS = 10
